### ISSUE TITLE
Fork vs Origin

### ISSUE THREAD

**Issue by geekdave** [prymitive/unsee#23]
Hey thanks for putting this out there, and for doing the React rewrite!

From your previous experience at Cloudflare, do you expect the original cloudflare/unsee repo to be maintained?  Might cause some confusion to have both versions around, if one of them is expected to just grow stale.

Perhaps the Cloudflare github contributors might consider archiving the original repo and including a friendly redirect note in the README to this one?

**Comment by prymitive** [comment]
I don't think that anyone will maintain the original repo, someone might merge small PRs but I doubt there will be any work put into it (there [wasn't that many contributors](https://github.com/cloudflare/unsee/graphs/contributors) internal or external anyway).
I do share the concern about the confusion, my plan was to rename the fork and disconnect it from the original repo on github (having docs on the history of the code instead), but I haven't found a good name yet. I'll need to do this before making a final React based release.
Does that sound like a good solution?

**Comment by geekdave** [comment]
👍 Sounds good!  Thanks!

**Comment by prymitive** [comment]
And that's done - https://github.com/prymitive/karma
